### ISSUE TITLE
EditText OnClickListener doesn't trigger?

### ISSUE THREAD

**Issue by Gaudon** [rey5137/material#144]
Attempting to give an edit text an onclicklistener whilst using 
focusable=false, 
clickable=true, 
editable=false

does not trigger onclick events unless you click outside of the region of the EditText (such as the label above the edit text).

Is there something I'm missing here?

**Comment by rey5137** [comment]
`com.rey.material.widget.EditText` is a class extends from `FrameLayout` and wraps a `android.widget.EditText`. You should retrieve the internal input view via `findViewById(int)` method (don't forget to set the viewId for it by `et_inputId` attribute), then set OnClickListener directly on it.

**Comment by Gaudon** [comment]
Understood. I was able to accomplish the same functionality by simply attaching an onFocusChange listener (editable=false). But I will remember this for the future, thanks.

**Comment by byanjati** [comment]
can I ask this issue once again ? because I don't understand in your statement "You should retrieve the internal input view via  findViewById(int)  method (don't forget to set the viewId for it by  et_inputId  attribute)" 

I attempt for setOnclick on EditText Material, but it can't triggered the click. Then i'm using onFocusChange, the problem is still exist, the current EditText cannot trigger the dialogshow.

**Comment by Gaudon** [comment]
There's likely something else going on if the onFocusChange listener isn't working.. if you just set the onClick for the edit text the region outside of the edittext box actually becomes clickable (like where the support labels would be found). This isn't ideal however, so I found using on FocusChange to be much more usuable and it works just fine.
