### ISSUE TITLE
onItemSelected

### ISSUE THREAD

**Issue by kmuralidharan91** [rey5137/material#181]
@rey5137 
Can anyone please help me how to use the spinner onItem Selected method?

@Override
    public void onItemSelected(com.rey.material.widget.Spinner spinner, View view, int i, long l) {
    //
    }

Previously i was using android's native spinner
    @Override
    public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
        String langCode =((Language)adapterView.getItemAtPosition(i)).getLanguageCode();
        Toast.makeText(adapterView.getContext(),langCode,Toast.LENGTH_SHORT).show();
        setLocale(langCode);
    }

how to change the onItemSelected method now???

Thanks in advance

**Comment by delebota** [comment]
Looking at the demo code it looks like you make an adapter that you assign to the spinner with the setAdapter method. Since the spinner gets passed into the method you should be able to use the getAdapter method to and do something similar to what you did with the native spinner.

Not sure if it will work for sure, but that's where I would start.

Demo code for spinners: https://github.com/rey5137/material/blob/master/app/src/main/java/com/rey/material/demo/SpinnersFragment.java

**Comment by w0pw0p** [comment]
@kmuralidharan91

This is how i've implemented the onselecteditemlistener.

     import android.view.View;
     import com.rey.material.widget.Spinner;
     import com.rey.material.widget.Spinner.OnItemSelectedListener;

     Spinner test = (Spinner) findViewById(R.id.test);
     test.setOnItemSelectedListener(new OnItemSelectedListener() {

               @Override
               public void onItemSelected(Spinner spinner, View view, int pos, long id)
               {
                     // Insert your codes here...
               }
     });

if you want to get the item selected, use the codes posted here. https://github.com/rey5137/material/issues/100

Thanks for @rey5137 for this wonderful library. :)
