### ISSUE TITLE
What will happen to the library when Android M is released ?

### ISSUE THREAD

**Issue by kmuralidharan91** [rey5137/material#201]
@rey5137 @rey5137 
How to stop the library being affected in Android Lollipop (Material design is needed other than L devices, so only we have to use this library) devices and What will happen when Android M is released with new design standards?

**Comment by andrewpros** [comment]
I think it is dead and without support, no single commit since 2 months, very risky to use.

**Comment by rey5137** [comment]
It isn't dead yet and I have published 1.2.1 version. I already used this library in my app, so I will occasionally add new feature or bug fix to it, but not so often because I have to do my main work.

FYI, you can create different styles for widgets on Android L and pre-L. And I think Android M is an update for Material Design, and I will add new widget or update exist ones if I find new design is interesting.
