### ISSUE TITLE
could not find material keystore file

### ISSUE THREAD

**Issue by VaishaliBhujbal** [rey5137/material#270]
Error:(17, 0) Could not find property 'MATERIAL_KEYSTORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.
<a href="openFile:C:\Users\VAISHALI\Downloads\material-master (1)\material-master\app\build.gradle">Open File</a>

![Uploading Capture.PNG…]()

**Comment by Binzzzz** [comment]
I was having the same problem and I've fixed it. I suppose this is a release build that can be build only for release and not for debugging purposes. just edit the release details in the gradle build file and try building again so that it switches to debugging mode, then you can run on your devices.
