### ISSUE TITLE
SimpleDialog onBuild method NullPointer on dialog.getView().findViewById(R.someid)

### ISSUE THREAD

**Issue by jlccaires** [rey5137/material#59]

**Comment by pavanjaju** [comment]
I am also having the same issue. Custom view are displayed properly, but when onBuild() we execute findViewById() on dialog object, it is always returning null.

**Comment by rey5137** [comment]
If you read the `Dialog.Builder` class's code, you will see that the `build(Context)` method call `onBuild(Context, int)` method first to retrieve a correct Dialog object, then after that apply some style like positive action, negative action, and custom content view. 

So that mean if you override `onBuild(Context, int)` method of `SimpleDialog.Builder` class, the Dialog object returned still not set custom view, therefore `findViewById(int)` return null. You should override `build(Context)` method instead.

May be I will add a `onAfterBuild()` method to `Dialog.Builder` class for convenient.

**Comment by pavanjaju** [comment]
Surely that will be more convenient. Will surely wait for onAfterBuild() method. Thanks :)

**Comment by jlccaires** [comment]
i will try, thanks.

**Comment by RenatoZevallos** [comment]
@jlccaires did you find the way ? I'm having the same issue.

**Comment by rey5137** [comment]
@RenatoZevallos I already posted the solution. And if you want, you can try `1.1.1-SNAPSHOT` version that I added `onBuildDone(Dialog)` method.

**Comment by jlccaires** [comment]
@RenatoZevallos I has overrided method build:
@Override
            public Dialog build(Context context) {
                Dialog dialog = super.build(context);
                tx = (EditText) dialog.findViewById(R.id.tx);

**Comment by RenatoZevallos** [comment]
@rey5137 where can i find that version? Cause i'm trying to compile it but it can't resolve: 
    Failed to resolve: com.github.rey5137:material:1.1.1-SNAPSHOT

@jlccaires thanks, I will try it =)

**Comment by RenatoZevallos** [comment]
@jlccaires thank you !! it works now =)

@rey5137 you're the man, regards

**Comment by jlccaires** [comment]
the credits are from @rey5137
